# Generated by Django 5.2.17 on 2026-09-09 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_recovery"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_sha256", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HourAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hour_start", models.DateTimeField(db_index=True)),
                ("consumption_kwh", models.FloatField()),
                ("feed_in_kwh", models.FloatField()),
                ("quarters", models.PositiveSmallIntegerField()),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hour_aggregates",
                        to="accounts.meterlink",
                    ),
                ),
            ],
            options={
                "ordering": ["hour_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("link", "hour_start"),
                        name="accounts_houraggregate_link_hour_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuarterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("consumption_kwh", models.FloatField()),
                ("feed_in_kwh", models.FloatField()),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarter_readings",
                        to="accounts.meterlink",
                    ),
                ),
            ],
            options={
                "ordering": ["measured_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("link", "measured_at"),
                        name="accounts_quarterreading_link_moment_unique",
                    )
                ],
            },
        ),
    ]
