"""The two routes that let a household's own meter reach its own advice.

The meter is seeded by running the real model at a known annual consumption
and writing its grid flows in as readings. That is what makes the accepting
test evidence: the figure the route has to arrive at is one this file chose,
and it is thirty percent away from the figure the account typed.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any

import numpy as np
import pytest
from django.utils import timezone
from helpers.accounts import TEST_PASSWORD

from accounts import service
from accounts.models import MeterLink, QuarterReading, User
from accounts.nl import CONSENT_TEXT_VERSION
from accounts.window import grid_epoch
from advice.models import StoredAdvice
from ampeer_sim.engine.run import simulate
from ampeer_sim.production.model import production_series
from ampeer_sim.production.pvgis import FallbackProvider
from ampeer_sim.profiles.compose import compose_consumption
from ampeer_sim.timebase import QUARTERS_PER_DAY, YearGrid
from ampeer_sim.types import Household, ProfileCategory, PVSystem

pytestmark = pytest.mark.django_db

EMAIL = "huishouden@voorbeeld.nl"
WEATHER_YEAR = 2023
PROFILE_YEAR = 2025
GRID = YearGrid.for_year(PROFILE_YEAR)

#: What the meter was generated at, and what the fit has to arrive at.
TRUE_ANNUAL_KWH = 4000.0

#: Eight weeks, which is more than the three the band needs and less than the
#: ninety days a quarter survives.
WINDOW_WEEKS = 8

BODY: dict[str, Any] = {
    "postcode4": "5401",
    "peak_power_wp": 3500,
    "azimuth_deg": 0,
    "tilt_deg": 35,
    "annual_consumption_kwh": TRUE_ANNUAL_KWH * 0.7,
    "daytime_occupancy": False,
    "has_ev": False,
    "ev_behaviour": None,
    "has_heat_pump": False,
    "heat_demand_kwh": None,
    "dynamic_contract": False,
    "has_battery": False,
    "battery_capacity_kwh": None,
}

SYSTEM = PVSystem(peak_power_wp=3500, azimuth_deg=0.0, tilt_deg=35.0)


class FlatProfiles:
    def fractions(self, year: int, category: ProfileCategory) -> np.ndarray:
        grid = YearGrid.for_year(year)
        return np.full(grid.quarters, 1.0 / grid.quarters)


@pytest.fixture(autouse=True)
def _offline_providers(monkeypatch: pytest.MonkeyPatch) -> None:
    """PVGIS and the NEDU file replaced on both paths that reach them.

    Two patches and not one. `advice.service` imported these names for the
    advice itself and `accounts.calibration` imported them for the fit, so
    patching either alone leaves the other reading a 13 MB CSV this test does
    not ship and calling a host this project refuses to call from a test.
    """

    def profiles() -> FlatProfiles:
        return FlatProfiles()

    def production(weather_year: int) -> FallbackProvider:
        return FallbackProvider(weather_year)

    for module in ("advice.service", "accounts.calibration"):
        monkeypatch.setattr(f"{module}.profile_provider", profiles)
        monkeypatch.setattr(f"{module}.production_provider", production)


def _csrf(client: Any) -> dict[str, str]:
    client.get("/api/auth/me/")
    return {"HTTP_X_CSRFTOKEN": client.cookies["csrftoken"].value}


def _register(client: Any, email: str = EMAIL) -> User:
    response = client.post(
        "/api/auth/register/",
        {
            "email": email,
            "password": TEST_PASSWORD,
            "consent_meter_link": True,
            "consent_lead_generation": False,
            "text_version": CONSENT_TEXT_VERSION,
        },
        content_type="application/json",
        **_csrf(client),
    )
    assert response.status_code == 201, response.content
    return User.objects.get(email=email)


def _year_import(annual_kwh: float) -> tuple[np.ndarray, np.ndarray]:
    household = Household(
        postcode4="5401", annual_consumption_kwh=annual_kwh, daytime_occupancy=False
    )
    hourly, temperature, _ = FallbackProvider(WEATHER_YEAR).hourly_series(
        household.postcode4, SYSTEM.azimuth_deg, SYSTEM.tilt_deg
    )
    production = production_series(hourly, SYSTEM, GRID, weather_year=WEATHER_YEAR)
    consumption = compose_consumption(
        household,
        GRID,
        FlatProfiles().fractions(GRID.year, household.profile_category),
        temperature,
        weather_year=WEATHER_YEAR,
        production_kwh=production,
    )
    flows = simulate(consumption, production)
    return flows.total_import, flows.total_export


def _give_the_account_a_meter(user: User, annual_kwh: float = TRUE_ANNUAL_KWH) -> MeterLink:
    """Eight weeks of readings, generated by the model at a known figure."""
    user.email_verified_at = timezone.now()
    user.save(update_fields=["email_verified_at"])
    link, _ = service.link_meter(user)

    imported, exported = _year_import(annual_kwh)
    epoch = grid_epoch(GRID)
    QuarterReading.objects.bulk_create(
        QuarterReading(
            link=link,
            measured_at=epoch + timedelta(minutes=15 * position),
            consumption_kwh=float(imported[position]),
            feed_in_kwh=float(exported[position]),
        )
        for position in range(WINDOW_WEEKS * 7 * QUARTERS_PER_DAY)
    )
    return link


def test_an_advice_asked_for_through_a_session_belongs_to_that_account(client: Any) -> None:
    user = _register(client)

    response = client.post(
        "/api/auth/advice/", BODY, content_type="application/json", **_csrf(client)
    )

    assert response.status_code == 201, response.content
    stored = StoredAdvice.objects.get(token=response.json()["token"])
    assert stored.owner == user


def test_without_a_meter_there_is_nothing_to_check(client: Any) -> None:
    """Silence, and an advice that is otherwise the ordinary one."""
    _register(client)

    response = client.post(
        "/api/auth/advice/", BODY, content_type="application/json", **_csrf(client)
    )

    body = response.json()
    assert body["consumption_check"] is None
    assert body["consumption_source"] == "TYPED"


def test_a_meter_that_disagrees_is_reported_with_its_band(client: Any) -> None:
    user = _register(client)
    _give_the_account_a_meter(user)

    response = client.post(
        "/api/auth/advice/", BODY, content_type="application/json", **_csrf(client)
    )

    check = response.json()["consumption_check"]
    assert check is not None
    assert check["typed_kwh"] == pytest.approx(TRUE_ANNUAL_KWH * 0.7)
    assert check["p50_kwh"] == pytest.approx(TRUE_ANNUAL_KWH, rel=0.02)
    assert check["p10_kwh"] < check["p50_kwh"] < check["p90_kwh"]
    assert str(round(TRUE_ANNUAL_KWH * 0.7)) in check["message"]


def test_a_meter_that_agrees_says_nothing(client: Any) -> None:
    """The band swallows a figure it does not contradict, and no constant said so."""
    user = _register(client)
    _give_the_account_a_meter(user)

    response = client.post(
        "/api/auth/advice/",
        BODY | {"annual_consumption_kwh": TRUE_ANNUAL_KWH},
        content_type="application/json",
        **_csrf(client),
    )

    assert response.json()["consumption_check"] is None


def test_accepting_recomputes_on_the_measured_figure(client: Any) -> None:
    """The whole point of the route, and the assertion that could fail.

    The account typed 2800 and the meter was generated at 4000. An accept that
    quietly reused the typed figure would leave `entered_consumption_kwh` at
    2800, and an accept that took the proposal's word for it without refitting
    would still have to arrive at the same place.
    """
    user = _register(client)
    _give_the_account_a_meter(user)
    first = client.post(
        "/api/auth/advice/", BODY, content_type="application/json", **_csrf(client)
    ).json()

    response = client.post(
        f"/api/auth/advice/{first['token']}/accept/",
        content_type="application/json",
        **_csrf(client),
    )

    assert response.status_code == 201, response.content
    body = response.json()
    assert body["token"] != first["token"]
    assert body["consumption_source"] == "MEASURED"
    assert body["confidence"] == "GOOD"
    # The year the answer was computed from. BODY carries no car and no heat
    # pump, so this is the accepted figure itself rather than it plus assets.
    assert body["modelled_consumption_kwh"]["value"] == pytest.approx(TRUE_ANNUAL_KWH, rel=0.02)
    assert first["modelled_consumption_kwh"]["value"] == pytest.approx(
        TRUE_ANNUAL_KWH * 0.7, rel=0.02
    )
    assert StoredAdvice.objects.get(token=body["token"]).owner == user


def test_accepting_an_advice_that_is_not_yours_is_not_found(client: Any) -> None:
    """Filtered on the owner, which is why the shareable token does not help."""
    owner = _register(client, "eigenaar@voorbeeld.nl")
    _give_the_account_a_meter(owner)
    theirs = client.post(
        "/api/auth/advice/", BODY, content_type="application/json", **_csrf(client)
    ).json()
    client.post("/api/auth/logout/", content_type="application/json", **_csrf(client))

    _register(client, "vreemde@voorbeeld.nl")
    response = client.post(
        f"/api/auth/advice/{theirs['token']}/accept/",
        content_type="application/json",
        **_csrf(client),
    )

    assert response.status_code == 404


def test_accepting_when_the_meter_no_longer_disagrees_is_refused(client: Any) -> None:
    """A proposal is about the meter now, so it can stop being true."""
    user = _register(client)
    _give_the_account_a_meter(user)
    first = client.post(
        "/api/auth/advice/", BODY, content_type="application/json", **_csrf(client)
    ).json()
    QuarterReading.objects.filter(link=MeterLink.active_for(user)).delete()

    response = client.post(
        f"/api/auth/advice/{first['token']}/accept/",
        content_type="application/json",
        **_csrf(client),
    )

    assert response.status_code == 400


def test_a_stranger_cannot_ask_for_an_owned_advice(client: Any) -> None:
    response = client.post(
        "/api/auth/advice/", BODY, content_type="application/json", **_csrf(client)
    )
    assert response.status_code == 401


def test_the_anonymous_calculator_is_untouched(client: Any) -> None:
    """This route was added beside the old one and not in front of it."""
    response = client.post(
        "/api/advice/estimate/",
        {
            "postcode4": "5401",
            "peak_power_wp": 3500,
            "azimuth_deg": 0,
            "tilt_deg": 35,
            "annual_consumption_kwh": 3500,
        },
        content_type="application/json",
    )
    assert response.status_code == 201, response.content
    assert "consumption_check" not in response.json()
    assert StoredAdvice.objects.get(token=response.json()["token"]).owner is None


def test_a_measurement_outside_the_window_is_ignored_by_the_fit(client: Any) -> None:
    """Backfill from another year must not move a figure about this one."""
    user = _register(client)
    link = _give_the_account_a_meter(user)
    QuarterReading.objects.create(
        link=link,
        measured_at=datetime(2022, 6, 1, 12, 0, tzinfo=UTC),
        consumption_kwh=99.0,
        feed_in_kwh=0.0,
    )

    check = client.post(
        "/api/auth/advice/", BODY, content_type="application/json", **_csrf(client)
    ).json()["consumption_check"]

    assert check is not None
    assert check["p50_kwh"] == pytest.approx(TRUE_ANNUAL_KWH, rel=0.02)
