# Generated by Django 5.2.17 on 2026-08-21 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    # RUF012 wants ClassVar on these two, and django-stubs types them as
    # instance attributes on the base, so the annotation it asks for is a mypy
    # error. Every generated migration hits it, so the exemption lives in
    # pyproject.toml under per-file-ignores rather than as a noqa on each line.
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("context", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="StoredAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("inputs", models.JSONField()),
                ("advice", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("postcode4", models.CharField(max_length=4)),
                ("azimuth_deg", models.SmallIntegerField()),
                ("tilt_deg", models.SmallIntegerField()),
                ("weather_year", models.SmallIntegerField()),
                ("production_w_per_kwp", models.BinaryField()),
                ("temperature_c", models.BinaryField()),
                ("source", models.CharField(max_length=16)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("postcode4", "azimuth_deg", "tilt_deg", "weather_year"),
                        name="unique_production_cache_key",
                    )
                ],
            },
        ),
    ]
