# Generated by Django 5.2.17 on 2026-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advice", "0003_production_cache_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                ("name", models.CharField(max_length=64)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("day", "name"), name="one_row_per_day_per_name")
                ],
            },
        ),
    ]
